### ISSUE TITLE
Auth fail on provisioned agent

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#196]
<p>I created a new managed disk azure image with sshd_config as follows:</p>

<p>PermitRootLogin without-password</p>

<p>AuthorizedKeysCommand /usr/local/bin/userkeys.sh</p>

<p>AuthorizedKeysCommandUser nobody</p>

<p>AuthorizedKeysFile .ssh/authorized_keys</p>

<p>ChallengeResponseAuthentication no</p>

<p>UsePAM yes</p>

<p>X11Forwarding yes</p>

<p>PrintMotd no</p>

<p>AcceptEnv LANG LC_*</p>

<p>Subsystem sftp /usr/lib/openssh/sftp-server</p>

<p>```</p>

<p>VM has user names `jenkins` with ssh keys to allow ssh key auth from Jenkins. Tested and working. </p>

<p> </p>

<p>When a template uses this image the VM is created and Auth fails</p>

<p>```</p>

<p> </p>

<p>{{2021-02-24 16:52:34.877+0000 <span class="error">&#91;id=464371&#93;</span>SEVERE  c.m.a.v.r.AzureVMAgentSSHLauncher#getRemoteSession: AzureVMAgentSSHLauncher: getRemoteSession: Got exception while connecting to remote host linux-image-test369e60.westeurope.cloudapp.azure.com:22<br/>
com.jcraft.jsch.JSchException: Auth fail<br/>
at com.jcraft.jsch.Session.connect(Session.java:512)<br/>
at com.jcraft.jsch.Session.connect(Session.java:183)<br/>
at com.microsoft.azure.vmagent.remote.AzureVMAgentSSHLauncher.getRemoteSession(AzureVMAgentSSHLauncher.java:307)<br/>
at com.microsoft.azure.vmagent.remote.AzureVMAgentSSHLauncher.connectToSsh(AzureVMAgentSSHLauncher.java:465)<br/>
at com.microsoft.azure.vmagent.remote.AzureVMAgentSSHLauncher.launch(AzureVMAgentSSHLauncher.java:115)<br/>
at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:294)<br/>
at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)<br/>
at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)<br/>
at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>
at java.lang.Thread.run(Thread.java:748)}}</p>

<p>```</p>

<p> </p>

<p>Other images created in the same manner works as expected. </p>

<p> </p>

<p>Debug of SSHD on VM which fails </p>

<p>```</p>

<p>Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2348&#93;</span>: debug1: Forked child 2399.<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: Set /proc/self/oom_score_adj to 0<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: rexec start in 5 out 5 newsock 5 pipe 7 sock 8<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: inetd sockets after dupping: 3, 3<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: Connection from 10.0.0.100 port 40088 on 10.43.240.4 port 22<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: Client protocol version 2.0; client software version JSCH-0.1.53<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: no match: JSCH-0.1.53<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: Local version string SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: permanently_set_uid: 107/65534 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: SSH2_MSG_KEXINIT sent <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: SSH2_MSG_KEXINIT received <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: kex: algorithm: ecdh-sha2-nistp256 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: kex: host key algorithm: ssh-rsa <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: expecting SSH2_MSG_KEX_ECDH_INIT <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: rekey after 4294967296 blocks <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: SSH2_MSG_NEWKEYS sent <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: expecting SSH2_MSG_NEWKEYS <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: SSH2_MSG_NEWKEYS received <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: rekey after 4294967296 blocks <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: KEX done <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: userauth-request for user jenkins service ssh-connection method none <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: attempt 0 failures 0 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: PAM: initializing for "jenkins"<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: PAM: setting PAM_RHOST to "10.0.0.100"<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: PAM: setting PAM_TTY to "ssh"<br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: userauth-request for user jenkins service ssh-connection method password <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: attempt 1 failures 0 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:34 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=10.0.0.100 user=jenkins<br/>
Feb 25 13:30:36 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: PAM: password authentication failed for jenkins: Authentication failure<br/>
Feb 25 13:30:36 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: Failed password for jenkins from 10.0.0.100 port 40088 ssh2<br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: error: Received disconnect from 10.0.0.100 port 40088:3: com.jcraft.jsch.JSchException: Auth fail <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: Disconnected from authenticating user jenkins 10.0.0.100 port 40088 <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: do_cleanup <span class="error">&#91;preauth&#93;</span><br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: monitor_read_log: child log fd closed<br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: do_cleanup<br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: PAM: cleanup<br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: Killing privsep child 2400<br/>
Feb 25 13:30:37 linux-image-test907690 sshd<span class="error">&#91;2399&#93;</span>: debug1: audit_event: unhandled event 12</p>

<p>```</p>

<p> </p>

<p> </p>
<i>[JENKINS-64959] created by hentis</i>

**Comment by henti** [comment]
Good day. It's been 2 months since I logged this issue which is blocking us from deploying new VMs. 

Any updates ?

**Comment by timja** [comment]
Hello,

I can confirm this plugin currently only supports username / password based authentication.

Other than that not sure exactly the issue
