### ISSUE TITLE
Cannot use plugin with existing storage account and secure transfer policy

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#209]
<p>Hi!</p>

<p>We are trying to use the plugin with an existing resource group and storage account but this is not working with one of our subscription because of a policy that force "secure transfer" enabled.</p>

<p>The storage account is already configured with secure transfer, but it seems that the plugin is trying to "change" the configuration of the storage account. Which fail with following error.</p>

<p>Same issue if trying to use a new storage account</p>

<p>This prevent us using the plugin <img class="emoticon" src="https://issues.jenkins.io/images/icons/emoticons/sad.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>Is it possible for example to have an option on the config to force the use of secure transfer and avoid issue with policies ?</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
AzureVMManagementServiceDelegate: deployment: Unable to deploy
com.microsoft.azure.CloudException: Status code 400, {<span class="code-quote">"error"</span>:{<span class="code-quote">"code"</span>:<span class="code-quote">"InvalidTemplateDeployment"</span>,<span class="code-quote">"message"</span>:<span class="code-quote">"The template deployment failed because of policy violation. Please see details <span class="code-keyword">for</span> more information."</span>,<span class="code-quote">"details"</span>:[{<span class="code-quote">"code"</span>:<span class="code-quote">"RequestDisallowedByPolicy"</span>,<span class="code-quote">"target"</span>:<span class="code-quote">"*********"</span>,<span class="code-quote">"message"</span>:<span class="code-quote">"Resource <span class="code-quote">'*****devop*****jenkins******'</span> was disallowed by policy. Policy identifiers: <span class="code-quote">'[{\"</span>policyAssignment\<span class="code-quote">":{\"</span>name\<span class="code-quote">":\"</span>Secure transfer to storage accounts should be enabled\<span class="code-quote">",\"</span>id\<span class="code-quote">":\"</span>/subscriptions<span class="code-comment">/*********/</span>providers/Microsoft.Authorization/policyAssignments/***********\<span class="code-quote">"},\"</span>policyDefinition\<span class="code-quote">":{\"</span>name\<span class="code-quote">":\"</span>Secure transfer to storage accounts should be enabled\<span class="code-quote">",\"</span>id\<span class="code-quote">":\"</span>/providers/Microsoft.Authorization/policyDefinitions/************\<span class="code-quote">"}},{\"</span>policyAssignment\<span class="code-quote">":{\"</span>name\<span class="code-quote">":\"</span>Secure transfer to storage accounts should be enabled\<span class="code-quote">",\"</span>id\<span class="code-quote">":\"</span>/providers/Microsoft.Management/managementGroups/********-***-mg/providers/Microsoft.Authorization/policyAssignments/************\<span class="code-quote">"},\"</span>policyDefinition\<span class="code-quote">":{\"</span>name\<span class="code-quote">":\"</span>Secure transfer to storage accounts should be enabled\<span class="code-quote">",\"</span>id\<span class="code-quote">":\"</span>/providers/Microsoft.Authorization/policyDefinitions/*************\<span class="code-quote">"}}]'</span>."</span>,<span class="code-quote">"additionalInfo"</span>:[{<span class="code-quote">"type"</span>:<span class="code-quote">"PolicyViolation"</span>,<span class="code-quote">"info"</span>:{<span class="code-quote">"policyDefinitionDisplayName"</span>:<span class="code-quote">"Secure transfer to storage accounts should be enabled"</span>,<span class="code-quote">"evaluationDetails"</span>:{<span class="code-quote">"evaluatedExpressions"</span>:[{<span class="code-quote">"result"</span>:<span class="code-quote">"True"</span>,<span class="code-quote">"expressionKind"</span>:<span class="code-quote">"Field"</span>,<span class="code-quote">"expression"</span>:<span class="code-quote">"type"</span>,<span class="code-quote">"path"</span>:<span class="code-quote">"type"</span>,<span class="code-quote">"expressionValue"</span>:<span class="code-quote">"Microsoft.Storage/storageAccounts"</span>,<span class="code-quote">"targetValue"</span>:<span class="code-quote">"Microsoft.Storage/storageAccounts"</span>,<span class="code-quote">"<span class="code-keyword">operator</span>"</span>:<span class="code-quote">"Equals"</span>},

</pre>
</div></div>

<p>Thanks in advance for the help!</p>

<p>Valentin</p>
<i>[JENKINS-61018] created by jonesbusy</i>

**Comment by AlphaWong** [comment]
My company is facing the same issue.
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/254 only fix the image call always comes with https 
While
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/188 ensure the newly created storage account will always come with 
```
"supportsHttpsTrafficOnly" = true
```
![image](https://user-images.githubusercontent.com/5622516/121639052-893ceb00-cabe-11eb-982d-e972b46128c5.png)

As https://github.com/jenkinsci/azure-vm-agents-plugin/pull/188 does not merge, I think release https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/760.ve25700ee68cc does not resolve this issue and the release should be changed to `support pull https os image` instead of  `Use https for accessing storage accounts`.

As only https://github.com/jenkinsci/azure-vm-agents-plugin/pull/188 update the field `"supportsHttpsTrafficOnly" = true` while provisioning newly storage account.
