### ISSUE TITLE
Not able to use custom image with associated plan (Marketplace image requires Plan information in the request' error)

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#222]
<p>Hello,</p>

<p>It's not possible to use a custom image with attached  plan (created from the Market place)</p>

<p>For example using RancherOS 1.5.1</p>
<ul>
	<li>Create an custom image using Packer (inject SSH keys, configure engine etc..)</li>
	<li>Use this custom image to start new machines using SSH</li>
</ul>

<p>We cannot do it because the API is expecting we pass the plan information in the request</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Creating a virtual machine from Marketplace image requires Plan information in the request
</pre>
</div></div>

<p>In case of packer it stores the plan information directly on the tags of the image</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">  <span class="code-quote">"tags"</span>: {
    <span class="code-quote">"PlanInfo"</span>: <span class="code-quote">"os"</span>,
    <span class="code-quote">"PlanProduct"</span>: <span class="code-quote">"rancheros"</span>,
    <span class="code-quote">"PlanPromotionCode"</span>: "",
    <span class="code-quote">"PlanPublisher"</span>: <span class="code-quote">"rancher"</span>,
    <span class="code-quote">"provisioned_by"</span>: <span class="code-quote">"packer"</span>
  },
</pre>
</div></div>

<p>Works if using the cli</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">az vm create --name whatever  --image /subscriptions/<whatever>/resourceGroups/<whatever>/providers/Microsoft.Compute/images/<my image> --plan-name os --plan-product rancheros --plan-publisher rancher 
</pre>
</div></div>

<p>So can we automatically get those information from Packer tag and pass them on the requestion ?</p>

<p>Or UI/configuration must be updated to enter those information to the user ?</p>

<p>Basically same of <a href="https://issues.jenkins.io/browse/JENKINS-52407" title="using marketplace image gives &#39;Creating a virtual machine from Marketplace image requires Plan information in the request&#39; error" class="issue-link" data-issue-key="JENKINS-52407"><del>JENKINS-52407</del></a> but for custom image, not only marketplace</p>

<p>Thanks again for the work on this plugin. It solve use many use cases!</p>
<i>[JENKINS-57469] created by jonesbusy</i>

**Comment by rpionke** [comment]
we got the same issue: `{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMMarketplaceInvalidInput","message":"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. VM: '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachines/jmeter-cntaa3af0'."}]}`

**Comment by hawaiik** [comment]
Just to share some more info same goes for gallery images that got customized and uploaded by packer to azure.

**Comment by Monishguru** [comment]
@timja @rpionke By any luck did you manage to find an alternate to provision the custom image based agent

**Comment by timja** [comment]
> @timja @rpionke By any luck did you manage to find an alternate to provision the custom image based agent

I have not looked into this as far as I remember.

**Comment by Monishguru** [comment]
@timja We are creating a custom vm image using CIS Hardened Image as base image.  Since CIS Base Hardened image is from azure market place, we are forced to provide the plan and publisher info when creating our custom image. Similarly when creating a VM out of the image. we are in need to provide the plan information and azure vm agents plugin from Jenkins is not able to pass this information. Please find the below error 

_**_Failed'.\",\"details\":[{\"code\":\"VMMarketplaceInvalidInput\",\"message\":\
Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request._**_ 


Just need to understand whether this enhancement will be prioritized or do we have some other alternate to achieve this VM Creation

**Comment by timja** [comment]
Hi contributions are welcomed, I have no plans to work on this in the short term but I can review a pull request

**Comment by smirgel** [comment]
Hi, I've run into this issue when trying to use a custom image base on RHEL 9.
I've been digging around the code and there definitely is some sort of support for plan info. It looks like it is supposed to be taken automatically from the image tags. It also seems that the code only does this if the image type is "custom" but not for "gallery", which is my case.
The tags are there (image is built with packer).
The expected tag names are "PlanPublisher", "PlanProduct" and "PlanInfo".

I'll see if I can scrape together a PR end of this week or beginning of next...
