### ISSUE TITLE
Key authentication for Azure Linux VM template

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#233]
<p>For now plugin supports only password-based authentication, I suggest to add private key authentication - it's more secure and de-facto standard today.</p>
<i>[JENKINS-55563] created by vitaly_il</i>

**Comment by fruch** [comment]
I have a use case that I have specialized images baked with specific ssh keys, 
so I can't use those images, since by default they disable user/pass auth.

**Comment by timja** [comment]
Contributions welcomed in that area, a lot of code can likely be lifted from the ec2 plugin.

I have no plans to work on it in the near future though, happy to review / test changes though.

**Comment by fruch** [comment]
> Contributions welcomed in that area, a lot of code can likely be lifted from the ec2 plugin.
> 
> I have no plans to work on it in the near future though, happy to review / test changes though.

Thanks @timja, would see if I'll have time to dive into it.

Seems like using AdvancedImage with ReferenceImage, with the exact specific requirements, take ~3min to start.
That's about 2 of installation that would be saved by using the specialized image.
I think I'll be able to live with that for a while...
