### ISSUE TITLE
Node stays suspended after node is started

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#238]
<p>We are currently using the Azure VM agents plugin for our CI/CD environment, we use custom images.</p>

<p>Our images are one of:</p>
<ul>
	<li>Image 1
	<ul>
		<li>Linux (With SSH launch)</li>
		<li>Idle retention time (10 min)</li>
		<li>Shutdown Only enabled</li>
	</ul>
	</li>
	<li>Image 2
	<ul>
		<li>Windows (With JNLP launch)</li>
		<li>Idle retention time (20 min)</li>
		<li>Shutdown Only enabled</li>
	</ul>
	</li>
</ul>

<p>Our issue is that we have an agent that successfully gets provisioned launched and is usable, after the idle timeout the node successfully shuts down and applies the <b>(offline)</b> and <b>(suspended)</b> flags to it correctly. Once another build comes along and attempts to use it, the plugin correctly launches the previously shutdown VM it starts correctly, connects correctly but it maintains the <b>(suspended)</b> flag making it unusable. I can manually fix it by issuing the following command in the Jenkins script console</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Jenkins.instance.getNode(<span class="code-quote">'azure-nodeXXXXXX'</span>).toComputer().setAcceptingTasks(<span class="code-keyword">true</span>);</pre>
</div></div>
<p>Then the build goes to the node and builds successfully, however if that command is not issued the build gets stuck waiting for the node to come online.</p>

<p>This issue happens with both types of images.</p>
<i>[JENKINS-54776] created by glokon</i>

**Comment by Minreaux** [comment]
Any update on this? This issue is still present on Jenkins v2.387.1 LTS using Azure VM Agents v825.v470cb_9e7361a_

**Comment by timja** [comment]
> Any update on this? This issue is still present on Jenkins v2.387.1 LTS using Azure VM Agents v825.v470cb_9e7361a_

can you explain your environment / problem more? I think this fixed it in most cases which is why people haven't been commenting for awhile.
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/185

**Comment by timja** [comment]
From what I can tell this was solved by https://github.com/jenkinsci/azure-vm-agents-plugin/pull/185
If there's another way to hit it please create a new issue, providing your configuration and the process it goes through to hit this issue
