### ISSUE TITLE
Add support for per-template max agents

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#249]
<p>We found ourselves in a <b>very</b> interesting position this morning on ci.jenkins.io!</p>

<p>We have a "Max Jenkins Agents limit" set to 50, and it turns out that when an influx of one type of Pipeline comes in, and requests an Agent matching a specific label, a denial of service can occur for <em>other</em> Pipelines which require other labels.</p>

<p>For example, if a pull request is merged on a repository which has 60 open pull requests, 60 new builds will (correctly) be queued. If those Pipelines are poorly configured, or run for an exceedingly long time, then a denial of service will occur for all other Pipelines on the system.</p>

<p>I would propose a solution would be to include optional per-template limits which ensure that no more than X of a specific template can be provisioned in the system</p>
<i>[JENKINS-50403] created by rtyler</i>

**Comment by tchrischan** [comment]
Would argue this is actually a bug not an enhancement now since the value can be set in the template. (Not sure if that makes a difference in priority.)
