### ISSUE TITLE
Only generalised images supported for shared image gallery

### ISSUE THREAD

**Issue by dVerhees** [jenkinsci/azure-vm-agents-plugin#268]
I've set up the plugin to use a custom VM image from a gallery I've created. The template checks are successful, but when triggering the agent deployment it fails after about 40 seconds with below error.

I've made sure the VM's are created in the same VNET as the Jenkins master and the security group allows ssh connections. 

Am I missing something here, or is there any more logging to be found? I would also like to know what AzureAD roles are required for the service principle. 

`Apr 08, 2021 2:41:36 PM INFO com.microsoft.azure.vmagent.AzureVMCloud createProvisionedAgent
AzureVMCloud: createProvisionedAgent: Waiting for deployment azurevm-jenkins-agent0408144135158 to be completed
Apr 08, 2021 2:42:07 PM SEVERE com.microsoft.azure.vmagent.AzureVMCloud$2 call
Failure creating provisioned agent 'azurevm-jenkins-agent827bf0'
com.microsoft.azure.vmagent.exceptions.AzureCloudException: AzureVMCloud: createProvisionedAgent: Deployment Failed: Microsoft.Compute/virtualMachines:azurevm-jenkins-agent827bf0 - BadRequest - com.microsoft.azure.management.resources.StatusMessage@19253759
	at com.microsoft.azure.vmagent.exceptions.AzureCloudException.create(AzureCloudException.java:37)
	at com.microsoft.azure.vmagent.AzureVMCloud.createProvisionedAgent(AzureVMCloud.java:594)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:844)
	at com.microsoft.azure.vmagent.AzureVMCloud$2.call(AzureVMCloud.java:822)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by timja** [comment]
Contributor is what's normally used

You can check the deployment in the Azure portal for more information, go to the resource group you're deploying to and then there will be deployments in the top right

**Comment by timja** [comment]
feel free to reply if more info needed but going to close this

**Comment by dVerhees** [comment]
Found the error message:
`Parameter 'osProfile' is not allowed.`

This seems to be caused by the fact that I'm using a specialized VM image, which includes user account and password and doesn't allow the account to be set during deployment. I guess this is not supported by the plugin?

**Comment by timja** [comment]
I guess, would need more details

**Comment by dVerhees** [comment]
It's related to this information:
https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries#generalized-and-specialized-images

which boils down to not setting the OSProfile when provisioning the VM.
https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?tabs=json#OSProfile

I guess when looking at the Plugin, we're now required to set admin credentials in the template, this should only be required for a generalized image, and make sure the "OSProfile" is not populated when the plugin creates the deployment.

On the other hand I'll try to figure out if I can use a Generalized image instead, but it could be useful for documentation that when using a shared image gallery, only Generalized Images are supported.

**Comment by timja** [comment]
Thanks!

I don't think there's a real reason that the admin credentials have to be in the template, a checkbox in the shared image gallery section for specialised image and then removing the osProfile and the adminUsername / password somewhere around here possibly:
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java#L558-L559

example of modifying the template:
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/AzureVMManagementServiceDelegate.java#L591-L601

This would be easier for someone else to contribute as I don't have a specialised image although instructions / a guide on how to make one could make it easier

**Comment by thst-nordic** [comment]
I've hit this problem today,   can the osProfile be omitted?

**Comment by Srinirap** [comment]
I am also hitting this problem any solution for this.?

**Comment by ramakrishnaraov** [comment]
I also experience the same issue while using specialized image. The osProfile is not allowed.

**Comment by ramakrishnaraov** [comment]
Hello @dVerhees , @thst-nordic , @Srinirap,
The support for specialized image is available in version 810 of the plugin.
Please validate if this is works for you too.
![image](https://user-images.githubusercontent.com/16054092/160053901-426ca9bd-44e7-48e5-8415-792a999914b3.png)
