### ISSUE TITLE
Latest version of Azure-Vm-Agent plugin is broken when using Managed Identity.

### ISSUE THREAD

**Issue by ryanberger-az** [jenkinsci/azure-vm-agents-plugin#278]
Jenkins version: 2.291
Running on OS: Ubuntu 18.04 LTS (in Azure)

We just updated the Azure-Vm-Agent plugin to the latest version and are noticing issues with the Region drop down not displaying results. We fully automate the creation of multiple VM Agent templates, where we pass through the Region into the JCasC.yaml for them. This has been working up until this update. 

`Parameter this.client.getSubscriptionId() is required and cannot be null.`

Upon further research of the logs and speaking with @timja - he believes this is an issue with the plugin operating when using Azure Managed Identities to facilitate the _**Jenkins <-> Azure**_ connection, which we are using. The error above can be seen over and over again in the logs after the update.

This video shows the drop down for Region to be not functional, even though this HAS a value in it via a JCasC configuration file (screenshot below)

https://user-images.githubusercontent.com/60238330/117693220-c9d9d980-b18b-11eb-8ea9-e07ba58dc0e3.mp4

![2021-05-10_11-43-24](https://user-images.githubusercontent.com/60238330/117693825-68663a80-b18c-11eb-8727-cd46212a3a07.png)

**Comment by timja** [comment]
@ryanberger-az https://github.com/jenkinsci/azure-vm-agents-plugin/pull/279 sets the subscription to the default one if one isn't set on your managed identity credential.

If your managed identity has access to more than subscription that won't work and you need to update your credential to specify which subscription to use.

**Comment by timja** [comment]
You do it on the Jenkins credential store not in Azure
