### ISSUE TITLE
Make windows agent with ssh work in a proxy environment

### ISSUE THREAD

**Issue by nirud** [jenkinsci/azure-vm-agents-plugin#296]
### Feature Request

Hi,

we are running in a corporate environment and because of some new rules, we need to go over a proxy if we want to access the internet from the azure networks.

That leads to problem for windows based agent with ssh connection, because the `sshInit.ps1` script tries to download OpenSSH from GitHub.

First, I tried to uncheck "Pre-Install SSH in Windows Agent" and to install OpenSSH in the custom initialization script. That did not work. Even if the checkbox is not ticked, it still tries to pre-install the SSH server.

I found the corresponding code in the class `AzureVMManagementServiceDelegate` line 253.
```
final boolean preInstallSshInWindows = properties.get("osType").equals(Constants.OS_TYPE_WINDOWS)
                    && properties.get("agentLaunchMethod").equals(Constants.LAUNCH_METHOD_SSH)
                    && (isBasic || referenceType == ImageReferenceType.REFERENCE
                    || template.getPreInstallSsh());
```
As long as you have a windows agent with ssh and a reference image, it will always be `true` no matter what the pre-install ssh value is.

I am not sure if this behaviour is indented, but I think the UI could be improved so that it is clear that the checkbox has no function in this case.

What I would like to do:

- Let me override the sshInit.ps1 somewhere. (For all VMs not just for one)
- or: Let me configure proxy information for the sshInit.ps1 script
- or: Let me configure an alternative URL for the OpenSSH-Win64.zip

**Comment by timja** [comment]
Can you test this change?
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/297

This will allow you to install it in your init script.

Adding an alternative URL is probably fine as well, I think I would just go for a system property though unless you think this needs a UI option?

---

Non-transparent proxies are the worst 😢

**Comment by nirud** [comment]
Of course I could test the change, but one remark before that:

Now the boolean `preInstallSshInWindows` would turn false, but also the boolean `useCustomScriptExtension` in line 258.
Wouldn't this mean no custom script extension is added to the vm and no script is run at all?

Changing the URL via a system property would be fine for me. I do not have an estimate how many companies forces a proxy in their azure networks, if this number is small I would go with the system property and keep the UI clean.

**Comment by timja** [comment]
not 100% sure to be honest
