### ISSUE TITLE
Enable verbose logging remote agent connection

### ISSUE THREAD

**Issue by smokingroosters** [jenkinsci/azure-vm-agents-plugin#302]
We are getting some weird communication error between the master and the agents provisioned by the plugin.
We would like to increase the verbosity of the logs of the remoting library as described [here](https://github.com/jenkinsci/remoting/blob/master/docs/logging.md) but It's not very clear to me how to pass CLI options to the remoting jar.
Same goes for trying to se the workingDir https://github.com/jenkinsci/remoting/blob/master/docs/workDir.md to allow the write of additional logs.

**Comment by timja** [comment]
@smokingroosters this should do it for you: https://github.com/jenkinsci/azure-vm-agents-plugin/pull/303

I haven't fully tested it yet but please try it out
