### ISSUE TITLE
VM Deployment Failed

### ISSUE THREAD

**Issue by kmkramer** [jenkinsci/azure-vm-agents-plugin#305]
### Version report

Jenkins and plugins versions report:
```
Jenkins 2.289.3
# Azure Credentials                   https://plugins.jenkins.io/azure-credentials
azure-credentials:190.v059127ae17bb
# Azure VM agents                     https://plugins.jenkins.io/azure-vm-agents
azure-vm-agents:789.va0c40e4d0070
```

- What Operating System are you using (both controller, and any agents involved in the problem)?
```
jenkins-lts-alpine (docker container)
```

### Reproduction steps

- Using either built-in Ubuntu image 20.04/16.04
- Tried different regions
- Tried Basic_A0/Standard_A0
- Storage_LRS

### Results

Expected result:

VM get created

Actual result:
From Azure, RG , Deployment logs
```
"code": "BadRequest",
      "message": "The selected VM size 'Basic_A0' cannot boot Hypervisor Generation '2'. If this was a Create operation please check that the Hypervisor Generation of the Image matches the Hypervisor Generation of the selected VM Size. If this was an Update operation please select a Hypervisor Generation '2' VM Size."
```

**Comment by timja** [comment]
Please use one of the v2 VMs:
https://docs.microsoft.com/en-us/azure/virtual-machines/generation-2
