### ISSUE TITLE
Not supporting Premium_LRS for vm even though the VM is supported with Premium_LRS

### ISSUE THREAD

**Issue by Srinirap** [jenkinsci/azure-vm-agents-plugin#339]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>
Azure VM Size: Standard_D8as_v4

  
  ```text
  The following errors occurred while validating the template.
1: The chosen storage type: Standard_LRS and the existing account type: Premium_LRS do not match.
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

Configure 
Azure VM Size : Standard_D8as_v4
Azure storage account: Premium_LRS

### Expected Results

It should be able to configure with Premium_LRS and I am able to achieve it through the Azure portal.

### Actual Results

Though I have selected the Standard_LRS getting the error.

**Comment by timja** [comment]
Can you be clearer on the issue? 

There's SKUs for multiple things, disk, storage account etc.

Can you provide a screenshot or config file please

**Comment by Srinirap** [comment]
I am building the VM from an exiting gallery image and using Dasv4-series but which supports PREMIUM_LRS and I am able to create VM using size Standard_D8as_v4 with PREMIUM SSD disk. But on the VM plugin config not getting the dropdown box of Premium_LRS.
![Screenshot 2022-02-23 at 8 40 46 PM](https://user-images.githubusercontent.com/44205368/155347687-e71177a7-6d7c-42c5-966a-e28387e7c4da.png)


Although when I chose Standard_D8s_v
![Screenshot 2022-02-23 at 8 43 10 PM](https://user-images.githubusercontent.com/44205368/155348001-42961761-5772-4c3a-b4f1-14bab6c3dff2.png)
4 it's showing the PREMIUM_LRS option.

**Comment by timja** [comment]
I've created a fix by just testing the regex in a regex tester, should work.

https://github.com/jenkinsci/azure-vm-agents-plugin/pull/340

Do you want to test it out before I merge?

**Comment by timja** [comment]
it'll get automatically released in 10-15 mins or so after merge
