### ISSUE TITLE
Could not initialize class com.azure.identity.implementation.IdentityClient

### ISSUE THREAD

**Issue by mohkhan-BRONGA** [jenkinsci/azure-vm-agents-plugin#343]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Latest jenkins version which is 2.319.3.

### Reproduction steps

1. Manage Jenkins
2. Manage clouds and nodes
3. Configure Clouds
4. Add new Cloud
5. Select Azure Cloud
6. Use existing credentials

### Expected Results

<img width="1220" alt="Screenshot 2022-03-09 at 5 38 57 PM" src="https://user-images.githubusercontent.com/79142868/157444636-fcc26682-6f69-45ae-b25a-5e17f8c14a83.png">

### Actual Results

![image](https://user-images.githubusercontent.com/79142868/157444688-e2d85dc6-37db-41ec-8572-35dd37257393.png)

**Comment by timja** [comment]
Please provide a full plugins report

Run this in the script console:

```
println("Jenkins: ${Jenkins.instance.getVersion()}")
println("OS: ${System.getProperty('os.name')} - ${System.getProperty('os.version')}")
println "---"

Jenkins.instance.pluginManager.plugins
  .collect()
  .sort { it.getShortName() }
  .each {
    plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
  }
return
```
