### ISSUE TITLE
New images claim they fail validation with null pointer result

### ISSUE THREAD

**Issue by limeman40** [jenkinsci/azure-vm-agents-plugin#361]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.348
OS: Linux - 5.4.0-1069-azure
---
Office-365-Connector:4.17.0
ace-editor:1.1
ansible:1.1
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
async-http-client:1.9.40.0
authentication-tokens:1.4
azure-acs:1.0.4
azure-ad:218.v90f6a_980b_a_61
azure-app-service:1.0.2
azure-artifact-manager:97.v074e1332e88d
azure-cli:0.9
azure-commons:1.1.3
azure-container-agents:241.va_780fa_dc374a_
azure-container-registry-tasks:0.6.5
azure-credentials:216.ve0b_4a_485ffc2
azure-credentials-ext:1.0
azure-function:0.3.3
azure-keyvault:136.veb1d1296db97
azure-sdk:106.v552de1e64d56
azure-vm-agents:816.v27bbb474b2b2
azure-vmss:0.2.4
badge:1.9.1
blackduck-detect:7.0.0
block-queued-job:0.2.0
blueocean-bitbucket-pipeline:1.25.5
blueocean-commons:1.25.5
blueocean-core-js:1.25.5
blueocean-jwt:1.25.5
blueocean-pipeline-api-impl:1.25.5
blueocean-pipeline-scm-api:1.25.5
blueocean-rest:1.25.5
blueocean-rest-impl:1.25.5
blueocean-web:1.25.5
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
changes-since-last-success:0.6
checks-api:1.7.4
cloud-stats:0.27
cloudbees-bitbucket-branch-source:773.v4b_9b_005b_562b_
cloudbees-folder:6.729.v2b_9d1a_74d673
command-launcher:84.v4a_97f2027398
conditional-buildstep:1.4.2
config-file-provider:3.10.0
copyartifact:1.46.4
credentials:1129.vef26f5df883c
credentials-binding:523.vd859a_4b_122e6
crx-content-package-deployer:1.9
datadog:4.0.0
digitalocean-plugin:1.3.0
display-url-api:2.3.6
docker-commons:1.19
docker-java-api:3.2.13-37.vf3411c9828b9
durable-task:496.va67c6f9eefa7
echarts-api:5.3.2-2
envinject:2.866.v5c0403e3d4df
envinject-api:1.199.v3ce31253ed13
extended-read-permission:3.2
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.1
font-awesome-api:6.1.1-1
generic-webhook-trigger:1.84
git:4.11.3
git-client:3.11.0
git-parameter:0.9.16
git-server:1.11
github:1.34.3
github-api:1.303-400.v35c2d8258028
github-branch-source:1637.vd833b_7ca_7654
github-pullrequest:0.4.0
gitlab-api:5.0.1-72.vb_8c272862e86
gitlab-branch-source:625.v85cf3a_400cfe
google-metadata-plugin:0.3.1
google-oauth-plugin:1.0.6
gradle:1.39
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
jackson2-api:2.13.3-285.vc03c0256d517
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.6-1
jdk-tool:1.5
jenkins-design-language:1.25.5
jersey2-api:2.35-8
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.7-3
jobConfigHistory:1146.v94c2521f9213
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.va_a_5e9068da_d7
kubernetes-cd:2.3.1
kubernetes-client-api:5.12.2-193.v26a_6078f65a_9
kubernetes-credentials:0.9.0
label-linked-jobs:6.0.1
ldap:2.10
lockable-resources:2.15
mailer:414.vcc4c33714601
mapdb-api:1.0.9.0
matrix-auth:3.1.2
matrix-project:771.v574584b_39e60
maven-plugin:3.19
mercurial:2.16.2
metrics:4.1.6.2
momentjs:1.1.1
msbuild:1.30
nexus-jenkins-plugin:3.14.415.v4605773547f3
node-iterator-api:1.5.1
node-sharing-executor:2.0.8
oauth-credentials:0.5
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.8
pipeline-build-step:2.18
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:591.v3a_7f422b_d058
pipeline-input-step:448.v37cea_9a_10a_70
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2086.v12b_420f036e5
pipeline-model-definition:2.2086.v12b_420f036e5
pipeline-model-extensions:2.2086.v12b_420f036e5
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2086.v12b_420f036e5
pipeline-stage-view:2.24
pipeline-utility-steps:2.12.2
plain-credentials:1.8
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
powershell:1.7
pubsub-light:1.16
resource-disposer:0.19
run-condition:1.5
saml:2.298.vc7a_2b_3958628
scm-api:608.vfa_f971c5a_a_e9
script-security:1175.v4b_d517d6db_f0
service-fabric:1.6
shelve-project-plugin:3.2
snakeyaml-api:1.30.1
ssh:2.6.1
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:277.v95c2fec1c047
ssh-slaves:1.814.vc82988f54b_10
ssh2easy:1.4
sshd:3.237.v883d165a_c1d3
stashNotifier:1.28
strict-crumb-issuer:2.1.0
structs:318.va_f3ccb_729b_71
synopsys-coverity:3.0.1
thinBackup:1.10
timestamper:1.17
token-macro:293.v283932a_0a_b_49
trilead-api:1.57.v6e90e07157e1
uno-choice:2.6.1
variant:1.4
windows-azure-storage:378.vb2cb9797e1e5
windows-slaves:1.8.1
workflow-aggregator:581.v0c46fa_697ffd
workflow-api:1164.v760c223ddb_32
workflow-basic-steps:948.v2c72a_091b_b_68
workflow-cps:2725.v7b_c717eb_12ce
workflow-cps-global-lib:588.v576c103a_ff86
workflow-durable-task-step:1144.vd77b_57189936
workflow-job:1186.v8def1a_5f3944
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:625.vd896b_f445a_f8
workflow-support:820.vd1a_6cc65ef33
ws-cleanup:0.42
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu Description:	Ubuntu 18.04.6 LTS

Does not matter issue happens with windows or linux images

### Reproduction steps

1. Create a new template using cloud configuration
2. Use existing Network Security Group
3. Click validate image
4. Get a null pointer error in the logs

### Expected Results

The VM image validation is sucessful

### Actual Results

Produces and null pointer.  Also will not spin up VM when trying to run a job with it this is the error that is thrown in the logs:

Invalid virtual machine image
java.lang.NullPointerException
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyVirtualMachineImage(AzureVMManagementServiceDelegate.java:2226)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.lambda$verifyTemplateAsync$2(AzureVMManagementServiceDelegate.java:2084)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

### Anything else?

It is working fine for an existing template that was setup months ago which is further odd behavior.  I am unable to make any new images and this is a big deal to me as I have other templates I wish to setup.

I am also seeing messages like the following:

Jun 07, 2022 1:14:57 PM WARNING com.microsoft.azure.vmagent.AzureVMCloudVerificationTask verify
AzureVMCloudVerificationTask: verify: powder-builder could not be verified:
Failed to validate the provided image location.
Jun 07, 2022 1:14:57 PM INFO com.microsoft.azure.vmagent.AzureVMCloud provision
Template powder-builder has just verified failed
Jun 07, 2022 1:14:57 PM INFO com.microsoft.azure.vmagent.AzureVMCloud provision

**Comment by limeman40** [comment]
I am also seeing this when I further test this:

Jun 07, 2022 5:29:08 PM INFO com.microsoft.azure.vmagent.AzureVMCloud provision
Failed to validate the provided image location.

When I try to spin up a VM from this image.. There is nothing wrong with this image though I can create a VM from it in Azure no issue.  Jenkins Azure Plugin just takes issue with it

**Comment by timja** [comment]
If you go to the service principal and click validate credential does it work?

**Comment by limeman40** [comment]
Yes other images work without issue. It appears to be any new images I try to setup as a template.

**Comment by limeman40** [comment]
Please let me know if I can provide any further details on this issue.  There is no issue with the service principle account please see below:

`Successfully verified Azure configuration.`

As I said this works fine for existing images.  Anything new seems to not work both linux or windows I get the same message on the backend:

`Verify configuration:
	resourceGroupName: rg-infra-devops;
	templateName: keli;
	labels: libclassifier keil;
	location: East US;
	virtualMachineSize: Standard_D8s_v5;
	storageAccountName: christielvm3505;
	noOfParallelJobs: 6;
	imageTopLevelType: advanced;
	builtInImage: Windows Server 2019;
	image: /subscriptions/5174e50a-382b-4a9b-8a02-bc27691b98c4/resourceGroups/rg-infra-devops/providers/Microsoft.Compute/images/keli-image-20220601090241;
	osType: Windows;
	id: ;
	publisher: ;
	offer: ;
	sku: ;
	version: latest;
	agentLaunchMethod: SSH;
	initScript: ;
	credentialsId: agent_admin_account;
	virtualNetworkName: Getway-vnet;
	virtualNetworkResourceGroupName: rg-infra-devops;
	subnetName: Gateway-snet;
	privateIP: true;
	nsgName: infra-devops-east-nsg;
	jvmOptions: ;
	galleryName: 
	galleryImageDefinition: 
	galleryImageVersion: 
	galleryResourceGroup: 
	gallerySubscriptionId: 
Jun 08, 2022 8:09:29 AM SEVERE com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate verifyVirtualMachineImage
Invalid virtual machine image
java.lang.NullPointerException
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyVirtualMachineImage(AzureVMManagementServiceDelegate.java:2226)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.lambda$verifyTemplateAsync$2(AzureVMManagementServiceDelegate.java:2084)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

There is nothing wrong with this image however as I can spin up a VM from it.  It seems to be on the plugin side of things as I see nothing in the Azure logs for this Resource Group.

**Comment by timja** [comment]
did you find a solution?

**Comment by limeman40** [comment]
It was something on my end. I noticed you can not verify a template before
you save the configuration.

I was able to make a windows and linux today and was able to spin them up
when tied as a label to a Jenkins job.
