### ISSUE TITLE
Add support for Collapse and Expand in Configure Clouds section

### ISSUE THREAD

**Issue by alwaysharsha** [jenkinsci/azure-vm-agents-plugin#369]
### What feature do you want to see added?

Add support for Collapse and Expand in Configure Clouds section, Currently If I have multiple Azure profile and images configured it would open as single page, if we can collapse and expand it would easy to navigate and use

**Comment by timja** [comment]
The plan is to implement this feature in clouds once merged for projects:
https://github.com/jenkinsci/jenkins/pull/6485

Would a sidebar achieve the same thing for you?
