### ISSUE TITLE
Using specific VMs & keeping them

### ISSUE THREAD

**Issue by KShoukry** [jenkinsci/azure-vm-agents-plugin#370]
### What feature do you want to see added?

I can't tell if this is already a feature. Basically we have 3 projects and because we are using Perforce & Unreal Engine. I can't use Agents that are created and deleted every time, because our builds would take an insane amount of time. 
Here is what I need:
- I want to be able to create a VM, using this plugin or manually, for project A.
- I want jobs with the Project A label to always use that VM. 
- I want Jenkins to automatically stop the VM in Azure after a specified amount of time & keep all configurations and disk data.
- I want Jenkins to be able to start the VM if Project A needs to be build and the VM is currently stopped.

Please let me know if all or any of these features are currently supported.

**Comment by timja** [comment]
It may be supported but I'm not sure how well it works, you could keep a pool of agents  and shutdown on idle.

There's issues raised around resuming, I've never really tested that part of the plugin.

This plugin has mostly been used around ephemeral agents to my knowledge but that's not to say it won't work

**Comment by KShoukry** [comment]
> It may be supported but I'm not sure how well it works, you could keep a pool of agents and shutdown on idle.
> 
> There's issues raised around resuming, I've never really tested that part of the plugin.
> 
> This plugin has mostly been used around ephemeral agents to my knowledge but that's not to say it won't work

Thank you for the response. If I just wanted 1 machine for each project would I set up 1 template per project? I guess I would also need to create a custom image that can support all of my projects since a clean Windows Image will not work for me.
