### ISSUE TITLE
Define what role should be assigned to the service principal in the documentation

### ISSUE THREAD

**Issue by tgquan67** [jenkinsci/azure-vm-agents-plugin#374]
### Describe your use-case which is not covered by existing documentation.

In the [prerequisites](https://plugins.jenkins.io/azure-vm-agents/#plugin-content-prerequisites) section of the documentation, it did not mention what kind of role or API permission should be assigned to the service principal. Is this an implicit requirement to assign the `Owner` role to it? And if that's the case, shouldn't we limit the amount of privilege this service principal is given to the bare minimum?

**Comment by timja** [comment]
if you can figure out what the permission is required and add to the documentation that would be helpful.

Contributor definitely works.

You may be able to get away with `Virtual Machine Contributor` but that would need testing

**Comment by tgquan67** [comment]
I guess I will need to test that out. `Owner` and `Contributor` are out, they give too much privilege.

**Comment by tgquan67** [comment]
So far it's working for me by assigning the service principal with `Virtual Machine Contributor` on subscription scope and `Contributor` on a resource group scope (the resource group where the VMs are deployed). The network, subnet and security group were created beforehand when I was making the template, so I just reused those.

**Comment by timja** [comment]
Why did you need `Virtual Machine Contributor` on the subscription scope?

**Comment by tgquan67** [comment]
Err, in the documentation it did not mention the scope, so I assumed that it was on the subscription scope?

**Comment by timja** [comment]
it should only need it on the resource group
