### ISSUE TITLE
Adding Custom Tags at Template level

### ISSUE THREAD

**Issue by jigyasapriyadarshini** [jenkinsci/azure-vm-agents-plugin#379]
@timja @mkrzywanski I am trying to add tags at the template level using Groovy Script. I tried using .withTags() for which accepted parameter data type is a list.
After trying to add something like 
![image](https://user-images.githubusercontent.com/20901180/210342242-a691182f-c9a9-4e10-ad5a-9b3a4afed1c5.png)
in my yaml file and using .withTags() in groovy script, I am unable to add the tags.
![image](https://user-images.githubusercontent.com/20901180/210342792-709678fc-c5e5-4de5-b45f-84fd2589be97.png)

Can you help me with the syntax for custom tags at template level? In case this can also be expanded at cloud config/ profile level then that too should help me.
Thank you.

**Comment by jigyasapriyadarshini** [comment]
@timja ,
I am using a Jenkins Job/ Jenkinsfile to trigger a playbook (PLAY1).
PLAY1 triggers a role to update cloud configuration in Jenkins and also reads some config variables from a vars yml file (tag variable is added here). The roles->role-name-folder->templates-folder consists of a groovy script written using the example provided in https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/README.md

In the vars yml file, variables are added to provide values associated with Azure Profile Configuration and template details associated with General Configuration. E.g. :

```
//azure profile configuration variables
cloud_name: "jpcloud"
azure_credential_id: "jpserviceprincipal"
azure_resource_group: "jprg"
azure_max_agents: 10
azure_deployment_timeout: 1200
```

```
//template variable examples
name: "jp-template"
description: ""
labels: "jp-vm"
location: "East US"
vm_size: "Standard_D2s_v3"
workspace: ""
os_type: "Linux"
launch_method: "ssh"
//a few more values here
```
  
**I want to add custom tags associated with Azure profile configuration and custom tags associated with Azure Template in vars yaml file.**

I tried adding tags like:
tags:
- name: "env"
- value: "jp-test-env"

in vars yaml file. 

I added .withTags() in groovy as per https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/src/main/java/com/microsoft/azure/vmagent/builders/AzureVMTemplateBuilder.java#L42.

Groovy script contains:
new AzureVMTemplateBuilder()
.withTags('{{template.tags}}')
//along with other with functions

But the template procurement is failing. Am I not adding the tag syntax correctly? As per my understanding .withTags will take a list variable with "AzureTagPair" data-type elements. 

Can you guide me with a correct syntax or example how can I add custom tags to my template?

Thank you.

**Comment by timja** [comment]
Again please provide a full example...

The tags are a list of kv pairs
you would need something like:

```
new AzureVMTemplateBuilder()
.withTags(List.of(new AzureTagPair("key", "value"), new AzureTagPair("key2", "value2")))
```

The configuration as code plugin should be easier to use as it's declarative rather than code

**Comment by jigyasapriyadarshini** [comment]
I have solved this now. This required explicit declaration of AzureTagPair variable and updating it.
Thanks.
