### ISSUE TITLE
When using Azure VM Pool Retention Strategy agents randomly disconnect

### ISSUE THREAD

**Issue by limeman40** [jenkinsci/azure-vm-agents-plugin#394]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
 Jenkins: 2.395
OS: Linux - 5.4.0-1104-azure
Java: 11.0.18 - Ubuntu (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:4.18.0
ace-editor:1.1
ansible:148.v6b_13c6de3a_47
ant:481.v7b_09e538fcca
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
async-http-client:1.9.40.0
authentication-tokens:1.4
azure-acs:1.0.4
azure-ad:313.v14b_f37ff114d
azure-app-service:1.0.2
azure-artifact-manager:109.vaf4232a14e2e
azure-cli:0.9
azure-commons:1.1.3
azure-container-agents:253.vd2f5cd5c5040
azure-container-registry-tasks:0.6.5
azure-credentials:254.v64da_8176c83a
azure-credentials-ext:1.0
azure-function:0.3.3
azure-keyvault:161.va_60991a_5d3d2
azure-sdk:118.v43f74dd9ca_dc
azure-vm-agents:825.v470cb_9e7361a_
azure-vmss:0.2.4
badge:1.9.1
blackduck-detect:8.0.0
block-queued-job:0.2.0
blueocean-bitbucket-pipeline:1.27.2
blueocean-commons:1.27.2
blueocean-core-js:1.27.2
blueocean-jwt:1.27.2
blueocean-pipeline-api-impl:1.27.2
blueocean-pipeline-scm-api:1.27.2
blueocean-rest:1.27.2
blueocean-rest-impl:1.27.2
blueocean-web:1.27.2
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.2-1
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-user-vars-plugin:1.9
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
changes-since-last-success:0.6
checks-api:1.8.1
cloud-stats:267.v577e3742c282
cloudbees-bitbucket-branch-source:796.v6cb_1559e1673
cloudbees-folder:6.815.v0dd5a_cb_40e0e
command-launcher:90.v669d7ccb_7c31
commons-httpclient3-api:3.1-3
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
conditional-buildstep:1.4.2
config-file-provider:3.11.1
copyartifact:686.v6fd37018d7c2
credentials:1224.vc23ca_a_9a_2cb_0
credentials-binding:523.vd859a_4b_122e6
crx-content-package-deployer:1.9
data-tables-api:1.13.3-2
datadog:5.3.0
digitalocean-plugin:1.3.1
display-url-api:2.3.7
docker-commons:419.v8e3cd84ef49c
docker-java-api:3.2.13-68.va_875df25a_b_45
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-2
envinject:2.901.v0038b_6471582
envinject-api:1.199.v3ce31253ed13
extended-read-permission:3.2
extensible-choice-parameter:1.8.0
external-monitor-job:203.v683c09d993b_9
favorite:2.4.1
font-awesome-api:6.3.0-1
generic-webhook-trigger:1.86.2
git:5.0.0
git-client:4.1.0
git-parameter:0.9.18
git-server:99.va_0826a_b_cdfa_d
github:1.37.0
github-api:1.303-417.ve35d9dd78549
github-branch-source:1701.v00cc8184df93
github-pullrequest:0.5.0
gitlab-api:5.0.1-78.v47a_45b_9f78b_7
gitlab-branch-source:646.vb_9560d64b_69f
google-metadata-plugin:0.4
google-oauth-plugin:1.0.7
gradle:2.3.2
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.31
instance-identity:142.v04572ca_5b_265
ionicons-api:31.v4757b_6987003
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-design-language:1.27.2
jersey2-api:2.39-1
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.16-2
jobConfigHistory:1207.vd28a_54732f92
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.3-1
jsch:0.1.55.61.va_e9ee26616e7
junit:1177.v90374a_ef4d09
kubernetes-cd:2.3.1
kubernetes-client-api:6.4.1-215.v2ed17097a_8e9
kubernetes-credentials:0.10.0
label-linked-jobs:6.0.1
ldap:671.v2a_9192a_7419d
lockable-resources:1131.vb_7c3d377e723
mailer:448.v5b_97805e3767
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.6
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.21
mercurial:1260.vdfb_723cdcc81
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
momentjs:1.1.1
msbuild:1.30
nexus-jenkins-plugin:3.16.481.ved9f5106e132
node-iterator-api:49.v58a_8b_35f8363
node-sharing-executor:2.0.8
oauth-credentials:0.5
okhttp-api:4.10.0-132.v7a_7b_91cef39c
pam-auth:1.10
pipeline-build-step:486.vd08f550cceee
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.1.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
powershell:2.0
pubsub-light:1.17
rebuild:1.34
resource-disposer:0.21
run-condition:1.5
saml:4.385.v4dea_91565e9d
scm-api:631.v9143df5b_e4a_a
script-security:1229.v4880b_b_e905a_6
service-fabric:1.6
shelve-project-plugin:3.2
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
ssh:2.6.1
ssh-agent:327.v230ecd01f86f
ssh-credentials:305.v8f4381501156
ssh-slaves:2.877.v365f5eb_a_b_eec
ssh2easy:1.4
sshd:3.275.v9e17c10f2571
stashNotifier:1.28
strict-crumb-issuer:2.1.0
structs:324.va_f5d6774f3a_d
synopsys-coverity:3.0.3
thinBackup:1.15
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
uno-choice:2.6.4
variant:59.vf075fe829ccb
windows-azure-storage:380.va3a027b784f4
windows-slaves:1.8.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3641.vf58904a_b_b_5d8
workflow-cps-global-lib:609.vd95673f149b_b
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1284.v2fe8ed4573d4
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: Ubuntu 18.04.6 LTS
Agent: Windows (Windows Server 2019 Datacenter) 
Agent: Linux (ubuntu 20.04)

### Reproduction steps

1. Let my gallery images spin up VMs to start the work day
2. Randomly see agents get disconnected sometimes in the middle of running jobs.
3. I then need to kill the job and restart it

### Expected Results

Have my VMs stay up and connected without any issues for the full day.

### Actual Results

VMs disconnect randomly throughout the day

### Anything else?

The cloud statistics page is filled with these kinds of messages:

`java.lang.Exception: Node ProvisioningActivity for AzureVMAgents/winagent/null (-1582658821) has lost. Mark as failure
	at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.cleanCloudStatistics(AzureVMAgentCleanUpTask.java:577)
	at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.clean(AzureVMAgentCleanUpTask.java:596)
	at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.lambda$execute$1(AzureVMAgentCleanUpTask.java:604)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

All these machines are in the same resource group and are using the same network security group with all the proper ports open.

I at first thought it might be some SSH timeout so I made some adjustments to sshd_config on both the Jenkins side and the agent side this did not solve the issue.

**Comment by limeman40** [comment]
I am also noticing this in the Jenkins logs:

Mar 16, 2023 4:32:03 PM INFO com.microsoft.azure.vmagent.AzureVMAgent deprovision
Deprovision called for agent linux-agent5de780, for reason: Node is being deleted by Jenkins after idle timeout

All my template configurations are setup for 24 hours though.

It also seems like I have two issues on being sometimes on spinning up the VMs they fail to spin up and throw the above error.

Other times they have been spun up for a while and randomly get disconnected while being in the middle of building a job.

**Comment by limeman40** [comment]
Any updates on this?

**Comment by timja** [comment]
I do not have the capacity to investigate issues like this.

If you are able to find a fix I am happy to review it.

**Comment by ryanberger-az** [comment]
More than likely you don’t have the proper access to your service
principal. If the vm deletion cannot occur; make sure the service principal
or managed identity you’re using to link your Jenkins to azure has
CONTRIBUTOR level access.

**Comment by limeman40** [comment]
@timja Is this related in any way to issue [#225](https://github.com/jenkinsci/azure-vm-agents-plugin/issues/225).

This issue was reported in 2019 and was never fixed as well.  I see the last note on it that you would look into it.

Also kind of curious if this plugin bugs are no longer being addressed.  I am counting upwards of 50 defects with no resolution.  Just curious if I am better off not using this plugin anymore.

**Comment by timja** [comment]
> Also kind of curious if this plugin bugs are no longer being addressed. I am counting upwards of 50 defects with no resolution. Just curious if I am better off not using this plugin anymore.

This plugin is used by 100s to 1000s of companies with no issues and is somewhat actively maintained.
Existing issues are not generally not worked on as to most people the plugin functionally works.

You or anyone is welcome to contribute a fix and it will be tested and released.

**Comment by limeman40** [comment]
I would if I even understand why this is happening.  I tried to increase logging today on the Azure logging in Jenkins but of course I did not really catch it happening today.

I see https://github.com/jenkinsci/azure-vm-agents-plugin/issues/225 was found back in 2019 and never solved.

**Comment by limeman40** [comment]
This issue turned out be windows update restarting the **VMs** I was able to apply something like this to the commands it runs on startup:

`# set the Windows Update service to "disabled"
sc.exe config wuauserv start=disabled

# stop the service, in case it is running
sc.exe stop wuauserv`

This seems to have fixed this issue.  I will now close this bug

**Comment by timja** [comment]
nice find!

**Comment by limeman40** [comment]
I only found this by logging in by bastion host.  We only assign private IPs to the Jenkins agents.

I then noticed the system had restarted for whatever reason.  Than I started digging into the event logs to look for Event IDs for reboots then I found it restarted due to a windows update.

Just wanted to put the solve in here in case anyone else runs into something like this.
