### ISSUE TITLE
Linux inbound agent sample script should run the agent as a service

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#409]
### What feature do you want to see added?

[Linux inbound agent sample script](https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/docs/init-scripts/linux-inbound-agent.sh) should run the agent as a systemd service so that if the VM reboots (or something else causes the process to die) the agent reconnects

### Upstream changes

see 
- https://github.com/jenkinsci/azure-vm-agents-plugin/pull/406

**Comment by dduportal** [comment]
A few notes out of my brain, for this feature:

- Would cloudinit be an option (as it's run on each restart on most cloud providers)?
- Support for non systemd distribution: WDYT mentioning it's not supported in the doc. ?

**Comment by timja** [comment]
> Would cloudinit be an option (as it's run on each restart on most cloud providers)?

could be but I was figuring why not just configure a systemd service as part of packer build / init script.
The windows example is here which sets it up a windows service and seems to work well:
https://raw.githubusercontent.com/timja/azure-vm-agents-plugin/linux-inbound-agent/docs/init-scripts/windows-inbound-agent.ps1

> Support for non systemd distribution: WDYT mentioning it's not supported in the doc. ?

The init script is up to administrators to configure either in the init script or as part of an image build.
I wouldn't say it's not supported just no example provided.
