### ISSUE TITLE
Option to enable Encryption at Host

### ISSUE THREAD

**Issue by eetu-n** [jenkinsci/azure-vm-agents-plugin#415]
### What feature do you want to see added?

A client's security policies require enabling encryption at host for all VMs, thus currently this plugin can't spawn any VMs in that environment.

Would adding a tickbox for this be possible?

**Comment by timja** [comment]
Looks straightforward: https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/2022-11-01/virtualmachines?pivots=deployment-language-arm-template

**Comment by timja** [comment]
> Seems it was! First contribution so hope I didn't do any style faux-pas etc.

thanks for the contribution!
