### ISSUE TITLE
Inbound: support for websockets

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/azure-vm-agents-plugin#421]
### What feature do you want to see added?

In https://github.com/jenkinsci/azure-vm-agents-plugin/pull/406, a new launch method for inbound agents on Linux was introduced.

The documentation states that it requires the TCP port for agent protocol to be set up, static and reachable.

I would like to be able to specify "Websockets" like I can do with permanent agents or Kubernetes agents, so the agent would connect to the controller through HTTP+Websockets to avoid setting up and opening this TCP port (which cannot be load balanced).

### Upstream changes

https://github.com/jenkinsci/azure-vm-agents-plugin/pull/406

**Comment by timja** [comment]
This makes sense although I think it could be worked around by explicitly telling it to use websockets in a similar manner to https://github.com/jenkinsci/azure-vm-agents-plugin/issues/422#issuecomment-1544727885

if you pass `-webSocket` using a similar command I think it would work

**Comment by dduportal** [comment]
Thanks I'm going to try the solution with init script, and if it works I'll send a documentation PR.

Same as https://github.com/jenkinsci/azure-vm-agents-plugin/issues/422#issuecomment-1545158636: it would we a nice UX if the end user could set up the agent through the UI and have it preconfigured (I guess passing userdata to the VM would help for this one, I'll give it a try as well).


> What do you mean by cannot be loadbalanced? You can't load balance Jenkins anyway?

The controller itself: no. But the route from the agent process location to a given controller can have many moving paths and my experience with the JNLP over TCP is such setup is not the most positive one, while websockets has embeded retries mechanisms (also, easier to expose as HTTP(s) already is and less configuration). 

But it's a nice to have of course :)

**Comment by timja** [comment]
> Same as [#422 (comment)](https://github.com/jenkinsci/azure-vm-agents-plugin/issues/422#issuecomment-1545158636): it would we a nice UX if the end user could set up the agent through the UI and have it preconfigured (I guess passing userdata to the VM would help for this one, I'll give it a try as well).

This was removed in Jenkins core in https://github.com/jenkinsci/jenkins/pull/8762

Documentation is being updated in https://github.com/jenkinsci/azure-vm-agents-plugin/pull/607
