### ISSUE TITLE
Inbound: support for TCP tunnel

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/azure-vm-agents-plugin#422]
### What feature do you want to see added?

Same as https://github.com/jenkinsci/azure-vm-agents-plugin/issues/421, except I would want to use a TCP tunnel (like permanent or Kubernetes agents are doing).

**Comment by timja** [comment]
You have full control of how you start the agent.

Just change your systemd service ExecStart to:

```
ExecStart=/usr/bin/java -cp /home/jenkins/inbound-agent/agent.jar hudson.remoting.jnlp.Main -headless -direct ${TUNNEL_ADDRESS} -workDir /home/jenkins/work -instanceIdentity ${INSTANCE_IDENTITY} @/home/${USER}/inbound-agent/agent-secret ${NODE_NAME}
```

**Comment by dduportal** [comment]
Thanks! It means it is technically feasible: I thought settings such as TCP tunnel, websockets, etc. would have to be set up when the "node" object is created in Jenkins side. Gotta try!


However, being able to configure this using the UI would improve the UX for users: same experience as a "permanent inbound agent" and the Kubernetes agents. Otherwise, we are rooting for yet another cloud and another way to configure agents. 
Does it make sense (even if not urgent or need another contributor)?

**Comment by dduportal** [comment]
> I guess you could have the controllers https port exposed but want to tunnel for the TCP port, but that just seems a bit odd.

I just had the case with trusted.ci.jenkins.io, the private controller used to generate update center and RPU data.
It is accessed with an SSH tunnel with the localhost's 1443 port of users pointing to the 443 of the service.
Jenkins location being set to `1443`, the jnlpUrl or HTTP direct access are all using the wrong port, while the 50000 is directly available (as a private port).


Of course there are other solution in this case (websocket I guess or changing the HTTPS port to 1443) but that is a real life example that other users could have on less flexible systems.

**Comment by timja** [comment]
That sounds like a misconfigured service, if users are expected to access it on 1443 Jenkins should be configured for that.

**Comment by timja** [comment]
> However, being able to configure this using the UI would improve the UX for users: same experience as a "permanent inbound agent"

This was removed in Jenkins core in https://github.com/jenkinsci/jenkins/pull/8762

Documentation is being updated in https://github.com/jenkinsci/azure-vm-agents-plugin/pull/607
