### ISSUE TITLE
Is it possible to use vm scale sets with this plugin?

### ISSUE THREAD

**Issue by JSIT-20** [jenkinsci/azure-vm-agents-plugin#444]
### What feature do you want to see added?

Haven't seen scale sets mentioned in the documentation, just want to inquire if it's possible to use them with this plugin

**Comment by timja** [comment]
It isn't currently, what benefit would it give?

I had a quick read of https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/overview and couldn't see anything that would benefit this plugin

**Comment by JSIT-20** [comment]
Functionally I don't think there would be any advantages, we just have some business restrictions that makes it easier for us to provision virtual machines using a scale set

**Comment by timja** [comment]
closing as answered
