### ISSUE TITLE
not able to use azureVMagent in pipeline script

### ISSUE THREAD

**Issue by jitkuthe** [jenkinsci/azure-vm-agents-plugin#477]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Centos7 / RHEL

### Reproduction steps

This is my sample pipeline where Iam using my existing vm and wanted to create a jenkins slave 
azureVmAgent(
                        azureCredentialsId: azureCredentials,
                        azureVmName: azureVmName,
                        azureVmResourceGroup: azureVmResourceGroup,
                        azureVmLocation: azureVmLocation,
                        azureVmImage: azureVmImage,
                        azureVmSize: azureVmSize,

### Expected Results

should have to add exixting vm as jenkins slave.

### Actual Results

[Pipeline] Start of Pipeline
[Pipeline] stage
[Pipeline] { (Launch Azure VM)
[Pipeline] script
[Pipeline] {
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 188e61cb-9ff8-4b1c-93d7-83ffe839bd3d
java.lang.NoSuchMethodError: No such DSL method 'azureVmAgent' found among steps [acceptGitLabMR, addGitLabMRComment, archive, bat, build,

**Comment by timja** [comment]
Why do you want to do this?

I don't think we want this in this plugin, and it's not a bug.
