### ISSUE TITLE
Add Retention strategy that destroys VMs that are not in use

### ISSUE THREAD

**Issue by limeman40** [jenkinsci/azure-vm-agents-plugin#486]
### What feature do you want to see added?

Can you make a "Retention strategy" that only keeps the VMs around if they are running jobs.  A nice added bonus would be if it could keep track if things where executing on a given agent and not destroy it if it is in use.

### Are you interested in contributing this feature?

no not really I am not that skilled in this code base.

**Comment by timja** [comment]
Isn't that the `Azure VM Once Retention Strategy` ?

Or do you want it to run every x minutes and only delete them then if they aren't running anything?

**Comment by damentz** [comment]
> Can you make a "Retention strategy" that only keeps the VMs around if they are running jobs

That's the idle retention policy.

>  A nice added bonus would be if it could keep track if things where executing on a given agent and not destroy it if it is in use.

That's built-in to Jenkins.  Running jobs prevent the running node/agent from being destroyed.  Once zero jobs are running the node can be destroyed.

Unless I'm missing something, everything you're asking for is already built into the plugin and this issue can be closed.
