### ISSUE TITLE
Change IP addresses to "Standard" SKU

### ISSUE THREAD

**Issue by SimonHarrisonSH** [jenkinsci/azure-vm-agents-plugin#501]
### What feature do you want to see added?

Azure is retiring Basic Public IP addresses from Sept of 2025. 
https://learn.microsoft.com/en-gb/azure/virtual-network/ip-services/public-ip-addresses#sku

Looking at my Azure console, the only Basic Public IP that I have is on a VM provisioned by the Azure VM Agents plugin.
Would it be possible to add an option of Basic/Standard (or just switch to Standard)?

I'd love to contibute, but sadly my Java knowledge is zero, and I also don't have a dev Jenkins instance to test on.

**Comment by timja** [comment]
Done in https://github.com/jenkinsci/azure-vm-agents-plugin/releases/tag/970.vb_34a_d99b_841a_
