### ISSUE TITLE
Azure agent templates throw "Agent template name must be unique" error and deletes the template after downloading JCasC configuration

### ISSUE THREAD

**Issue by Minreaux** [jenkinsci/azure-vm-agents-plugin#504]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
Jenkins: 2.426.3
OS: Linux - 6.2.0-1019-azure
Java: 11.0.21 - Ubuntu (OpenJDK 64-Bit Server VM)
---
ansicolor:1.0.4
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
azure-artifact-manager:143.v2b4c2c2d63e5
azure-credentials:312.v0f3973cd1e59
azure-keyvault:237.v301692369180
azure-sdk:157.v855da_0b_eb_dc2
azure-vm-agents:901.ved986df424b_3
bootstrap5-api:5.3.2-3
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1148.vce12cfcdf090
build-user-vars-plugin:1.9
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:336.v788e4055508b_
cloudbees-folder:6.858.v898218f3609d
command-launcher:107.v773860566e2e
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
configuration-as-code:1775.v810dc950b_514
copyartifact:722.v0662a_9b_e22a_c
credentials:1319.v7eb_51b_3a_c97b_
credentials-binding:657.v2b_19db_7d6e6d
dark-theme:416.v535839b_c4e88
dashboard-view:2.508.va_74654f026d1
data-tables-api:1.13.8-2
display-url-api:2.200.vb_9327d658781
durable-task:550.v0930093c4b_a_6
echarts-api:5.4.3-2
favorite:2.208.v91d65b_7792a_c
font-awesome-api:6.5.1-2
git:5.2.1
git-client:4.6.0
github:1.38.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1772.va_69eda_d018d4
gson-api:2.10.1-15.v0d99f670e0a_7
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.1-373.ve709c6871598
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jjwt-api:0.11.5-77.v646c772fddb_0
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-1
jsch:0.2.16-86.v42e010d9484b_
json-api:20240205-27.va_007549e895c
json-path-api:2.9.0-33.v2527142f2e1d
junit:1259.v65ffcef24a_88
lockable-resources:1232.v512d6c434eb_d
mailer:463.vedf8358e006b_
matrix-auth:3.2.1
matrix-project:822.824.v14451b_c0fd42
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
nunit:485.ve8a_85357320d
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
p4:1.14.4
parameter-separator:166.vd0120849b_386
parameterized-scheduler:262.v00f3d90585cc
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-graph-view:215.vc0ea_557e4d6f
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2175.v76a_fff0a_2618
pipeline-model-definition:2.2175.v76a_fff0a_2618
pipeline-model-extensions:2.2175.v76a_fff0a_2618
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2175.v76a_fff0a_2618
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:143.v1b_df8b_d3b_e48
plugin-util-api:3.8.0
pollscm:1.5
prism-api:1.29.0-10
resource-disposer:0.23
saml:4.464.vea_cb_75d7f5e0
scm-api:683.vb_16722fb_b_80b_
script-security:1326.vdb_c154de8669
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.948.vb_8050d697fec
sshd:3.322.v159e91f6a_550
structs:337.v1b_04ea_4df7c8
swarm:3.44
theme-manager:215.vc1ff18d67920
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.133.vfb_8a_7b_9c5dd1
uno-choice:2.8.1
variant:60.v7290fc0eb_b_cd
versioncolumn:233.v2d198f8212a_2
windows-azure-storage:419.v4046cd70d2e3
workflow-aggregator:596.v8c21c963d92d
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3853.vb_a_490d892963
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1385.vb_58b_86ea_fff1
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:415.v434365564324
workflow-step-api:657.v03b_e8115821b_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04 LTS

### Reproduction steps

1. Create a new Azure agent template at your Jenkins instance https://\<your-jenkins-url\>/manage/cloud/\<your-azure-cloud\>/new
2. Save the template with any settings
3. Modify the template and save it again
4. Notice that the template can be modified and can save without issue
5. Go to your JCasC page https://\<your-jenkins-url\>/manage/configuration-as-code/
6. Select "Download Configuration"
7. Go back to your Jenkins Azure templates page https://\<your-jenkins-url\>/manage/cloud/\<your-azure-cloud\>/templates and select the same template you created earlier
8. Modify the template and save it again
9. Notice that the template throws "agent template must be unique" error
10. Go back to your Jenkins Azure templates page https://\<your-jenkins-url\>/manage/cloud/\<your-azure-cloud\>/templates
11. Notice that the template you created and attempted to modify is now gone

### Expected Results

After clicking the "Download Configuration" button for JCasC, I can modify existing Azure agent templates and save them without issue.

### Actual Results

After clicking the "Download Configuration" button for JCasC, attempting to modify existing Azure agent templates and saving them throws the "agent template must be unique" error and deletes the template.

### Anything else?

Here's a screenshot of the error: ![image](https://github.com/jenkinsci/azure-vm-agents-plugin/assets/9372700/f95c9b9b-bce8-4dc3-bdb9-f6c4dc9ed1d8)

Looks like this error was caused by the changes made in this PR: https://github.com/jenkinsci/azure-vm-agents-plugin/pull/493. Or at least that's when the "agent template must be unique" error was introduced.

**Comment by Minreaux** [comment]
@timja tagging if you have any ideas for the cause of this issue. This one caught me off guard when I was modifying a template and then it suddenly deleted itself. Thankfully I could re-create it easily.

**Comment by johnl2323** [comment]
I have this same issue on my Jenkins deployments.  Any update on the defect or a workaround?

**Comment by timja** [comment]
Hi just a note to say I was able to reproduce this, thanks for the bug report.

**Comment by johnl2323** [comment]
I retested with azure-vm-agents-plugin version 954.ve27457dda_dc9 on LTS 2.462.1 and the issue was resolved.  Thanks!
