### ISSUE TITLE
AzureVMAgent template donot have attribute to set license_type

### ISSUE THREAD

**Issue by Lathavrp** [jenkinsci/azure-vm-agents-plugin#506]
### What feature do you want to see added?

No attribute available to set license type as "windows_client/windows_server" for the agents launching with AzureSSHLauncher

**Comment by timja** [comment]
Can you explain with more context or links? I don't know what this license type is.

**Comment by Lathavrp** [comment]
Sorry for the late response, could not respond due to family sickness

License type attribute not available to set value as “windows_client/windows_server” for the jenkins vm agents with AzureVMAgent plugin and AzureSSHLauncher(preInstallSsh) template
Ref"[azure-vm-agents-plugin/src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java at 638564a4422c6a53b28b18099357f7929f9b5f20 · jenkinsci/azure-vm-agents-plugin · GitHub](https://github.com/jenkinsci/azure-vm-agents-plugin/blob/638564a4422c6a53b28b18099357f7929f9b5f20/src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java)

We are running jenkins in K8s cluster deployed as helm chart and JCACS configuration on Azure.

This attribute is available, while we are creating VM via terraform
[How to deploy Windows 11 on Azure - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/windows-desktop-multitenant-hosting-deployment#verify-your-vm-is-utilizing-the-licensing-benefit)

**Comment by Lathavrp** [comment]
Hello @timja any support here to add license_type attribute/field something like  OsType or osDiskSize 
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/638564a4422c6a53b28b18099357f7929f9b5f20/src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java#L1091
