### ISSUE TITLE
JNLP connection to Azure VM Fails

### ISSUE THREAD

**Issue by mkthakral** [jenkinsci/azure-vm-agents-plugin#526]
### Jenkins and plugins versions report

Jenkins: 2.361.1
OS: Windows Server 2016 - 10.0
Java: 11.0.14 - Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM)

azure-credentials:242.vb_f9c4fa_6b_2b_6
azure-sdk:118.v43f74dd9ca_dc
azure-vm-agents:822.v3a18fc3d2de1

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Windows Server 2016
Agent: Windows 10

### Reproduction steps

1. Run a Jenkins pipeline and create Windows 10 agent on Azure using JNLP connection

### Expected Results

Controller to connect to Azure VM

### Actual Results

VM gets connected but JNLP connection fails with no clear error message

### Anything else?

SSH connection works fine. JNLP does not. We have set port 1025 open between Jenkins controller and agent for TCP connection.

### Are you interested in contributing a fix?

Sure

**Comment by timja** [comment]
Are you using this init script?
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/master/docs/init-scripts/windows-inbound-agent.ps1

You can try modify it to not run as a service and to run it in the foreground, you might be able to save / view the logs in an easier way that way.

If you run the script on the VM itself what happens?

**Comment by mkthakral** [comment]
Sorry but when I should run this script? After the agent VM is created? Run it manually? Or this script has to be mentioned in Jenkins -> Manage Node & Clouds section?

if I run a script similar to this manually on the agent VM, the agent gets connected to Controller. But that can not be the solution as we create and destroy VM on the go with CI pipelines.

**Comment by mkthakral** [comment]
Thank you so much. It solved my problem :)
