### ISSUE TITLE
Issue using a custom image sourced from a Marketplace image

### ISSUE THREAD

**Issue by raavendanp** [jenkinsci/azure-vm-agents-plugin#583]
### What feature do you want to see added?

Add the option to add  Plan information when using image from Gallery Image. Otherwise this error will occur.
"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request"

If there is a workarround to fix this please close this issue with the solution.

**Comment by timja** [comment]
Its supposed to work based on https://github.com/jenkinsci/azure-vm-agents-plugin/pull/452

Can you please refile this as a bug which will ask for more information for looking into this:
https://github.com/jenkinsci/azure-vm-agents-plugin/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=1-report-bug.yml

If you can provide full steps to reproduce including building of the image then it will be more likely this can be sorted

**Comment by raavendanp** [comment]
Created https://github.com/jenkinsci/azure-vm-agents-plugin/issues/584

I review the PR https://github.com/jenkinsci/azure-vm-agents-plugin/pull/452 but it don't understand how it works using the jenkins UI as there is not field to add that information. Nor with custom tags.
