### ISSUE TITLE
Plan Information option does not appear when using "custom user image" or "gallery image"

### ISSUE THREAD

**Issue by raavendanp** [jenkinsci/azure-vm-agents-plugin#584]
### Jenkins and plugins versions report

<details>
  <summary>Environment: Gov Virginia Cloud</summary>

  
  ```text
  When try to use custom user image or gallery image option, there is no field to add Plan Information. This generate the error
"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. "
  ```
![Image](https://github.com/user-attachments/assets/c74ee5a3-b3a1-4eef-9c34-a510bc753ebd)
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

1. Create agent template
2. Use custom user image 

### Expected Results

Have a plan information field to add to the request

### Actual Results

Error
"Creating a virtual machine from Marketplace image or a custom image sourced from a Marketplace image requires Plan information in the request. "

**Comment by timja** [comment]
Thanks, 

Looking at https://github.com/jenkinsci/azure-vm-agents-plugin/pull/452 it was just for gallery image but the person who created it thought it worked for the others.

Is there any chance you can try it in an image gallery?

**Comment by raavendanp** [comment]
With image gallery I have the same problem, there is no plan information field.
![Image](https://github.com/user-attachments/assets/7033837c-0c0b-4a99-8836-e7aca0e5976c)

**Comment by timja** [comment]
The plan information should be on the image tags from what I understand:

These are:
* PlanInfo
* PlanProduct
* PlanPublisher

If those tags are present then they will be copied and provided in the request, I've checked and the same should work for custom image as well as gallery image

**Comment by raavendanp** [comment]
Okay I still having the problem. My image comes from a virtual machine with this as blank
![Image](https://github.com/user-attachments/assets/f6bed778-7b5a-438e-af62-eedda251a0a9)

So I add the tags this way

![Image](https://github.com/user-attachments/assets/3ac0e6d4-ed02-4786-b738-f8e0ca3d1124)

Even leaving as blank I still having the proble, is there something I am missing?

**Comment by timja** [comment]
Its not the tags in Jenkins its the tags on the image, are you able to add those tags to the image?

**Comment by raavendanp** [comment]
Thank you for the clarification! I can keep working with this now
